#!/usr/bin/env bash
# Install nginx web server

echo -e "Updating and installing Nginx.\n"
sudo apt-get update -y -qq && \
	 sudo apt-get install nginx -y

echo -e "\nSetting up some minor stuff.\n"

# starting nginx service
sudo service nginx start

sudo ufw allow 'Nginx HTTP'

sudo chown -R "$USER":"$USER" /var/log/html
sudo chmod -R 755 /var/log

cp /var/www/log/index.nginx-debian.html /var/log/html/index.nginx-debian.html.bckp

echo -e "Hello World!" | dd status=none of=/var/log/html/index.nginx-debian.html

sudo service nginx restart

echo -e "\nCompleted. ✅\n"t
