#!/usr/bin/env bash
# To debug nginx, the service (init) should indicate that nginx is not currently running.
sed -i 's/8080/80/g' /etc/nginx/sites-enabled/default
service nginx restart
pkill -o nginx
